package be.ceau.nace;

public enum Class {

	_1_11(Group._01_1, "Growing of cereals (except rice), leguminous crops and oil seeds"),
	_1_12(Group._01_1, "Growing of rice"),
	_1_13(Group._01_1, "Growing of vegetables and melons, roots and tubers"),
	_1_14(Group._01_1, "Growing of sugar cane"),
	_1_15(Group._01_1, "Growing of tobacco"),
	_1_16(Group._01_1, "Growing of fibre crops"),
	_1_19(Group._01_1, "Growing of other non-perennial crops"),
	_1_21(Group._01_2, "Growing of grapes"),
	_1_22(Group._01_2, "Growing of tropical and subtropical fruits"),
	_1_23(Group._01_2, "Growing of citrus fruits"),
	_1_24(Group._01_2, "Growing of pome fruits and stone fruits"),
	_1_25(Group._01_2, "Growing of other tree and bush fruits and nuts"),
	_1_26(Group._01_2, "Growing of oleaginous fruits"),
	_1_27(Group._01_2, "Growing of beverage crops"),
	_1_28(Group._01_2, "Growing of spices, aromatic, drug and pharmaceutical crops"),
	_1_29(Group._01_2, "Growing of other perennial crops"),
	_1_3(Group._01_3, "Plant propagation"),
	_1_41(Group._01_4, "Raising of dairy cattle"),
	_1_42(Group._01_4, "Raising of other cattle and buffaloes"),
	_1_43(Group._01_4, "Raising of horses and other equines"),
	_1_44(Group._01_4, "Raising of camels and camelids"),
	_1_45(Group._01_4, "Raising of sheep and goats"),
	_1_46(Group._01_4, "Raising of swine/pigs"),
	_1_47(Group._01_4, "Raising of poultry"),
	_1_49(Group._01_4, "Raising of other animals"),
	_1_5(Group._01_5, "Mixed farming"),
	_1_61(Group._01_6, "Support activities for crop production"),
	_1_62(Group._01_6, "Support activities for animal production"),
	_1_63(Group._01_6, "Post-harvest crop activities"),
	_1_64(Group._01_6, "Seed processing for propagation"),
	_1_7(Group._01_7, "Hunting, trapping and related service activities"),
	_2_1(Group._02_1, "Silviculture and other forestry activities"),
	_2_2(Group._02_2, "Logging"),
	_2_3(Group._02_3, "Gathering of wild growing non-wood products"),
	_2_4(Group._02_4, "Support services to forestry"),
	_3_11(Group._03_1, "Marine fishing"),
	_3_12(Group._03_1, "Freshwater fishing"),
	_3_21(Group._03_2, "Marine aquaculture"),
	_3_22(Group._03_2, "Freshwater aquaculture"),
	_5_1(Group._05_1, "Mining of hard coal"),
	_5_2(Group._05_2, "Mining of lignite"),
	_6_1(Group._06_1, "Extraction of crude petroleum"),
	_6_2(Group._06_2, "Extraction of natural gas"),
	_7_1(Group._07_1, "Mining of iron ores"),
	_7_21(Group._07_2, "Mining of uranium and thorium ores"),
	_7_29(Group._07_2, "Mining of other non-ferrous metal ores"),
	_8_11(Group._08_1, "Quarrying of ornamental and building stone, limestone, gypsum, chalk and slate"),
	_8_12(Group._08_1, "Operation of gravel and sand pits; mining of clays and kaolin"),
	_8_91(Group._08_9, "Mining of chemical and fertiliser minerals"),
	_8_92(Group._08_9, "Extraction of peat"),
	_8_93(Group._08_9, "Extraction of salt"),
	_8_99(Group._08_9, "Other mining and quarrying n.e.c."),
	_9_1(Group._09_1, "Support activities for petroleum and natural gas extraction"),
	_9_9(Group._09_9, "Support activities for other mining and quarrying"),
	_10_11(Group._10_1, "Processing and preserving of meat"),
	_10_12(Group._10_1, "Processing and preserving of poultry meat"),
	_10_13(Group._10_1, "Production of meat and poultry meat products"),
	_10_2(Group._10_2, "Processing and preserving of fish, crustaceans and molluscs"),
	_10_31(Group._10_3, "Processing and preserving of potatoes"),
	_10_32(Group._10_3, "Manufacture of fruit and vegetable juice"),
	_10_39(Group._10_3, "Other processing and preserving of fruit and vegetables"),
	_10_41(Group._10_4, "Manufacture of oils and fats"),
	_10_42(Group._10_4, "Manufacture of margarine and similar edible fats"),
	_10_51(Group._10_5, "Operation of dairies and cheese making"),
	_10_52(Group._10_5, "Manufacture of ice cream"),
	_10_61(Group._10_6, "Manufacture of grain mill products"),
	_10_62(Group._10_6, "Manufacture of starches and starch products"),
	_10_71(Group._10_7, "Manufacture of bread; manufacture of fresh pastry goods and cakes"),
	_10_72(Group._10_7, "Manufacture of rusks and biscuits; manufacture of preserved pastry goods and cakes"),
	_10_73(Group._10_7, "Manufacture of macaroni, noodles, couscous and similar farinaceous products"),
	_10_81(Group._10_8, "Manufacture of sugar"),
	_10_82(Group._10_8, "Manufacture of cocoa, chocolate and sugar confectionery"),
	_10_83(Group._10_8, "Processing of tea and coffee"),
	_10_84(Group._10_8, "Manufacture of condiments and seasonings"),
	_10_85(Group._10_8, "Manufacture of prepared meals and dishes"),
	_10_86(Group._10_8, "Manufacture of homogenised food preparations and dietetic food"),
	_10_89(Group._10_8, "Manufacture of other food products n.e.c."),
	_10_91(Group._10_9, "Manufacture of prepared feeds for farm animals"),
	_10_92(Group._10_9, "Manufacture of prepared pet foods"),
	_11_01(Group._11__, "Distilling, rectifying and blending of spirits"),
	_11_02(Group._11__, "Manufacture of wine from grape"),
	_11_03(Group._11__, "Manufacture of cider and other fruit wines"),
	_11_04(Group._11__, "Manufacture of other non-distilled fermented beverages"),
	_11_05(Group._11__, "Manufacture of beer"),
	_11_06(Group._11__, "Manufacture of malt"),
	_11_07(Group._11__, "Manufacture of soft drinks; production of mineral waters and other bottled waters"),
	_12__(Group._12__, "Manufacture of tobacco products"),
	_13_1(Group._13_1, "Preparation and spinning of textile fibres"),
	_13_2(Group._13_2, "Weaving of textiles"),
	_13_3(Group._13_3, "Finishing of textiles"),
	_13_91(Group._13_9, "Manufacture of knitted and crocheted fabrics"),
	_13_92(Group._13_9, "Manufacture of made-up textile articles, except apparel"),
	_13_93(Group._13_9, "Manufacture of carpets and rugs"),
	_13_94(Group._13_9, "Manufacture of cordage, rope, twine and netting"),
	_13_95(Group._13_9, "Manufacture of non-wovens and articles made from non-wovens, except apparel"),
	_13_96(Group._13_9, "Manufacture of other technical and industrial textiles"),
	_13_99(Group._13_9, "Manufacture of other textiles n.e.c."),
	_14_11(Group._14_1, "Manufacture of leather clothes"),
	_14_12(Group._14_1, "Manufacture of workwear"),
	_14_13(Group._14_1, "Manufacture of other outerwear"),
	_14_14(Group._14_1, "Manufacture of underwear"),
	_14_19(Group._14_1, "Manufacture of other wearing apparel and accessories"),
	_14_2(Group._14_2, "Manufacture of articles of fur"),
	_14_31(Group._14_3, "Manufacture of knitted and crocheted hosiery"),
	_14_39(Group._14_3, "Manufacture of other knitted and crocheted apparel"),
	_15_11(Group._15_1, "Tanning and dressing of leather; dressing and dyeing of fur"),
	_15_12(Group._15_1, "Manufacture of luggage, handbags and the like, saddlery and harness"),
	_15_2(Group._15_2, "Manufacture of footwear"),
	_16_1(Group._16_1, "Sawmilling and planing of wood"),
	_16_21(Group._16_2, "Manufacture of veneer sheets and wood-based panels"),
	_16_22(Group._16_2, "Manufacture of assembled parquet floors"),
	_16_23(Group._16_2, "Manufacture of other builders' carpentry and joinery"),
	_16_24(Group._16_2, "Manufacture of wooden containers"),
	_16_29(Group._16_2, "Manufacture of other products of wood; manufacture of articles of cork, straw and plaiting materials"),
	_17_11(Group._17_1, "Manufacture of pulp"),
	_17_12(Group._17_1, "Manufacture of paper and paperboard"),
	_17_21(Group._17_2, "Manufacture of corrugated paper and paperboard and of containers of paper and paperboard"),
	_17_22(Group._17_2, "Manufacture of household and sanitary goods and of toilet requisites"),
	_17_23(Group._17_2, "Manufacture of paper stationery"),
	_17_24(Group._17_2, "Manufacture of wallpaper"),
	_17_29(Group._17_2, "Manufacture of other articles of paper and paperboard"),
	_18_11(Group._18_1, "Printing of newspapers"),
	_18_12(Group._18_1, "Other printing"),
	_18_13(Group._18_1, "Pre-press and pre-media services"),
	_18_14(Group._18_1, "Binding and related services"),
	_18_2(Group._18_2, "Reproduction of recorded media"),
	_19_1(Group._19_1, "Manufacture of coke oven products"),
	_19_2(Group._19_2, "Manufacture of refined petroleum products"),
	_20_11(Group._20_1, "Manufacture of industrial gases"),
	_20_12(Group._20_1, "Manufacture of dyes and pigments"),
	_20_13(Group._20_1, "Manufacture of other inorganic basic chemicals"),
	_20_14(Group._20_1, "Manufacture of other organic basic chemicals"),
	_20_15(Group._20_1, "Manufacture of fertilisers and nitrogen compounds"),
	_20_16(Group._20_1, "Manufacture of plastics in primary forms"),
	_20_17(Group._20_1, "Manufacture of synthetic rubber in primary forms"),
	_20_2(Group._20_2, "Manufacture of pesticides and other agrochemical products"),
	_20_3(Group._20_3, "Manufacture of paints, varnishes and similar coatings, printing ink and mastics"),
	_20_41(Group._20_4, "Manufacture of soap and detergents, cleaning and polishing preparations"),
	_20_42(Group._20_4, "Manufacture of perfumes and toilet preparations"),
	_20_51(Group._20_5, "Manufacture of explosives"),
	_20_52(Group._20_5, "Manufacture of glues"),
	_20_53(Group._20_5, "Manufacture of essential oils"),
	_20_59(Group._20_5, "Manufacture of other chemical products n.e.c."),
	_20_6(Group._20_6, "Manufacture of man-made fibres"),
	_21_1(Group._21_1, "Manufacture of basic pharmaceutical products"),
	_21_2(Group._21_2, "Manufacture of pharmaceutical preparations"),
	_22_11(Group._22_1, "Manufacture of rubber tyres and tubes; retreading and rebuilding of rubber tyres"),
	_22_19(Group._22_1, "Manufacture of other rubber products"),
	_22_21(Group._22_2, "Manufacture of plastic plates, sheets, tubes and profiles"),
	_22_22(Group._22_2, "Manufacture of plastic packing goods"),
	_22_23(Group._22_2, "Manufacture of builders’ ware of plastic"),
	_22_29(Group._22_2, "Manufacture of other plastic products"),
	_23_11(Group._23_1, "Manufacture of flat glass"),
	_23_12(Group._23_1, "Shaping and processing of flat glass"),
	_23_13(Group._23_1, "Manufacture of hollow glass"),
	_23_14(Group._23_1, "Manufacture of glass fibres"),
	_23_19(Group._23_1, "Manufacture and processing of other glass, including technical glassware"),
	_23_2(Group._23_2, "Manufacture of refractory products"),
	_23_31(Group._23_3, "Manufacture of ceramic tiles and flags"),
	_23_32(Group._23_3, "Manufacture of bricks, tiles and construction products, in baked clay"),
	_23_41(Group._23_4, "Manufacture of ceramic household and ornamental articles"),
	_23_42(Group._23_4, "Manufacture of ceramic sanitary fixtures"),
	_23_43(Group._23_4, "Manufacture of ceramic insulators and insulating fittings"),
	_23_44(Group._23_4, "Manufacture of other technical ceramic products"),
	_23_49(Group._23_4, "Manufacture of other ceramic products"),
	_23_51(Group._23_5, "Manufacture of cement"),
	_23_52(Group._23_5, "Manufacture of lime and plaster"),
	_23_61(Group._23_6, "Manufacture of concrete products for construction purposes"),
	_23_62(Group._23_6, "Manufacture of plaster products for construction purposes"),
	_23_63(Group._23_6, "Manufacture of ready-mixed concrete"),
	_23_64(Group._23_6, "Manufacture of mortars"),
	_23_65(Group._23_6, "Manufacture of fibre cement"),
	_23_69(Group._23_6, "Manufacture of other articles of concrete, plaster and cement"),
	_23_7(Group._23_7, "Cutting, shaping and finishing of stone"),
	_23_91(Group._23_9, "Production of abrasive products"),
	_23_99(Group._23_9, "Manufacture of other non-metallic mineral products n.e.c."),
	_24_1(Group._24_1, "Manufacture of basic iron and steel and of ferro-alloys "),
	_24_2(Group._24_2, "Manufacture of tubes, pipes, hollow profiles and related fittings, of steel"),
	_24_31(Group._24_3, "Cold drawing of bars"),
	_24_32(Group._24_3, "Cold rolling of narrow strip"),
	_24_33(Group._24_3, "Cold forming or folding"),
	_24_34(Group._24_3, "Cold drawing of wire"),
	_24_41(Group._24_4, "Precious metals production"),
	_24_42(Group._24_4, "Aluminium production"),
	_24_43(Group._24_4, "Lead, zinc and tin production"),
	_24_44(Group._24_4, "Copper production"),
	_24_45(Group._24_4, "Other non-ferrous metal production"),
	_24_46(Group._24_4, "Processing of nuclear fuel "),
	_24_51(Group._24_5, "Casting of iron"),
	_24_52(Group._24_5, "Casting of steel"),
	_24_53(Group._24_5, "Casting of light metals"),
	_24_54(Group._24_5, "Casting of other non-ferrous metals"),
	_25_11(Group._25_1, "Manufacture of metal structures and parts of structures"),
	_25_12(Group._25_1, "Manufacture of doors and windows of metal"),
	_25_21(Group._25_2, "Manufacture of central heating radiators and boilers"),
	_25_29(Group._25_2, "Manufacture of other tanks, reservoirs and containers of metal"),
	_25_3(Group._25_3, "Manufacture of steam generators, except central heating hot water boilers"),
	_25_4(Group._25_4, "Manufacture of weapons and ammunition"),
	_25_5(Group._25_5, "Forging, pressing, stamping and roll-forming of metal; powder metallurgy"),
	_25_61(Group._25_6, "Treatment and coating of metals"),
	_25_62(Group._25_6, "Machining"),
	_25_71(Group._25_7, "Manufacture of cutlery"),
	_25_72(Group._25_7, "Manufacture of locks and hinges"),
	_25_73(Group._25_7, "Manufacture of tools"),
	_25_91(Group._25_9, "Manufacture of steel drums and similar containers"),
	_25_92(Group._25_9, "Manufacture of light metal packaging "),
	_25_93(Group._25_9, "Manufacture of wire products, chain and springs"),
	_25_94(Group._25_9, "Manufacture of fasteners and screw machine products"),
	_25_99(Group._25_9, "Manufacture of other fabricated metal products n.e.c."),
	_26_11(Group._26_1, "Manufacture of electronic components"),
	_26_12(Group._26_1, "Manufacture of loaded electronic boards"),
	_26_2(Group._26_2, "Manufacture of computers and peripheral equipment"),
	_26_3(Group._26_3, "Manufacture of communication equipment"),
	_26_4(Group._26_4, "Manufacture of consumer electronics"),
	_26_51(Group._26_5, "Manufacture of instruments and appliances for measuring, testing and navigation"),
	_26_52(Group._26_5, "Manufacture of watches and clocks"),
	_26_6(Group._26_6, "Manufacture of irradiation, electromedical and electrotherapeutic equipment"),
	_26_7(Group._26_7, "Manufacture of optical instruments and photographic equipment"),
	_26_8(Group._26_8, "Manufacture of magnetic and optical media"),
	_27_11(Group._27_1, "Manufacture of electric motors, generators and transformers"),
	_27_12(Group._27_1, "Manufacture of electricity distribution and control apparatus"),
	_27_2(Group._27_2, "Manufacture of batteries and accumulators"),
	_27_31(Group._27_3, "Manufacture of fibre optic cables"),
	_27_32(Group._27_3, "Manufacture of other electronic and electric wires and cables"),
	_27_33(Group._27_3, "Manufacture of wiring devices"),
	_27_4(Group._27_4, "Manufacture of electric lighting equipment"),
	_27_51(Group._27_5, "Manufacture of electric domestic appliances"),
	_27_52(Group._27_5, "Manufacture of non-electric domestic appliances"),
	_27_9(Group._27_9, "Manufacture of other electrical equipment"),
	_28_11(Group._28_1, "Manufacture of engines and turbines, except aircraft, vehicle and cycle engines"),
	_28_12(Group._28_1, "Manufacture of fluid power equipment"),
	_28_13(Group._28_1, "Manufacture of other pumps and compressors"),
	_28_14(Group._28_1, "Manufacture of other taps and valves"),
	_28_15(Group._28_1, "Manufacture of bearings, gears, gearing and driving elements"),
	_28_21(Group._28_2, "Manufacture of ovens, furnaces and furnace burners"),
	_28_22(Group._28_2, "Manufacture of lifting and handling equipment"),
	_28_23(Group._28_2, "Manufacture of office machinery and equipment (except computers and peripheral equipment)"),
	_28_24(Group._28_2, "Manufacture of power-driven hand tools"),
	_28_25(Group._28_2, "Manufacture of non-domestic cooling and ventilation equipment"),
	_28_29(Group._28_2, "Manufacture of other general-purpose machinery n.e.c."),
	_28_3(Group._28_3, "Manufacture of agricultural and forestry machinery"),
	_28_41(Group._28_4, "Manufacture of metal forming machinery"),
	_28_49(Group._28_4, "Manufacture of other machine tools"),
	_28_91(Group._28_9, "Manufacture of machinery for metallurgy"),
	_28_92(Group._28_9, "Manufacture of machinery for mining, quarrying and construction"),
	_28_93(Group._28_9, "Manufacture of machinery for food, beverage and tobacco processing"),
	_28_94(Group._28_9, "Manufacture of machinery for textile, apparel and leather production"),
	_28_95(Group._28_9, "Manufacture of machinery for paper and paperboard production"),
	_28_96(Group._28_9, "Manufacture of plastics and rubber machinery"),
	_28_99(Group._28_9, "Manufacture of other special-purpose machinery n.e.c."),
	_29_1(Group._29_1, "Manufacture of motor vehicles"),
	_29_2(Group._29_2, "Manufacture of bodies (coachwork) for motor vehicles; manufacture of trailers and semi-trailers"),
	_29_31(Group._29_3, "Manufacture of electrical and electronic equipment for motor vehicles"),
	_29_32(Group._29_3, "Manufacture of other parts and accessories for motor vehicles"),
	_30_11(Group._30_1, "Building of ships and floating structures"),
	_30_12(Group._30_1, "Building of pleasure and sporting boats"),
	_30_2(Group._30_2, "Manufacture of railway locomotives and rolling stock"),
	_30_3(Group._30_3, "Manufacture of air and spacecraft and related machinery"),
	_30_4(Group._30_4, "Manufacture of military fighting vehicles"),
	_30_91(Group._30_9, "Manufacture of motorcycles"),
	_30_92(Group._30_9, "Manufacture of bicycles and invalid carriages"),
	_30_99(Group._30_9, "Manufacture of other transport equipment n.e.c."),
	_31_01(Group._31__, "Manufacture of office and shop furniture"),
	_31_02(Group._31__, "Manufacture of kitchen furniture"),
	_31_03(Group._31__, "Manufacture of mattresses"),
	_31_09(Group._31__, "Manufacture of other furniture"),
	_32_11(Group._32_1, "Striking of coins"),
	_32_12(Group._32_1, "Manufacture of jewellery and related articles"),
	_32_13(Group._32_1, "Manufacture of imitation jewellery and related articles"),
	_32_2(Group._32_2, "Manufacture of musical instruments"),
	_32_3(Group._32_3, "Manufacture of sports goods"),
	_32_4(Group._32_4, "Manufacture of games and toys"),
	_32_5(Group._32_5, "Manufacture of medical and dental instruments and supplies"),
	_32_91(Group._32_9, "Manufacture of brooms and brushes"),
	_32_99(Group._32_9, "Other manufacturing n.e.c. "),
	_33_11(Group._33_1, "Repair of fabricated metal products"),
	_33_12(Group._33_1, "Repair of machinery"),
	_33_13(Group._33_1, "Repair of electronic and optical equipment"),
	_33_14(Group._33_1, "Repair of electrical equipment"),
	_33_15(Group._33_1, "Repair and maintenance of ships and boats"),
	_33_16(Group._33_1, "Repair and maintenance of aircraft and spacecraft"),
	_33_17(Group._33_1, "Repair and maintenance of other transport equipment"),
	_33_19(Group._33_1, "Repair of other equipment"),
	_33_2(Group._33_2, "Installation of industrial machinery and equipment"),
	_35_11(Group._35_1, "Production of electricity"),
	_35_12(Group._35_1, "Transmission of electricity"),
	_35_13(Group._35_1, "Distribution of electricity"),
	_35_14(Group._35_1, "Trade of electricity"),
	_35_21(Group._35_2, "Manufacture of gas"),
	_35_22(Group._35_2, "Distribution of gaseous fuels through mains"),
	_35_23(Group._35_2, "Trade of gas through mains"),
	_35_3(Group._35_3, "Steam and air conditioning supply"),
	_36(Group._36__, "Water collection, treatment and supply"),
	_37(Group._37__, "Sewerage"),
	_38_11(Group._38_1, "Collection of non-hazardous waste"),
	_38_12(Group._38_1, "Collection of hazardous waste"),
	_38_21(Group._38_2, "Treatment and disposal of non-hazardous waste"),
	_38_22(Group._38_2, "Treatment and disposal of hazardous waste"),
	_38_31(Group._38_3, "Dismantling of wrecks"),
	_38_32(Group._38_3, "Recovery of sorted materials"),
	_39(Group._39__, "Remediation activities and other waste management services"),
	_41_1(Group._41_1, "Development of building projects"),
	_41_2(Group._41_2, "Construction of residential and non-residential buildings"),
	_42_11(Group._42_1, "Construction of roads and motorways"),
	_42_12(Group._42_1, "Construction of railways and underground railways"),
	_42_13(Group._42_1, "Construction of bridges and tunnels"),
	_42_21(Group._42_2, "Construction of utility projects for fluids"),
	_42_22(Group._42_2, "Construction of utility projects for electricity and telecommunications"),
	_42_91(Group._42_9, "Construction of water projects"),
	_42_99(Group._42_9, "Construction of other civil engineering projects n.e.c."),
	_43_11(Group._43_1, "Demolition"),
	_43_12(Group._43_1, "Site preparation"),
	_43_13(Group._43_1, "Test drilling and boring"),
	_43_21(Group._43_2, "Electrical installation"),
	_43_22(Group._43_2, "Plumbing, heat and air-conditioning installation"),
	_43_29(Group._43_2, "Other construction installation"),
	_43_31(Group._43_3, "Plastering"),
	_43_32(Group._43_3, "Joinery installation"),
	_43_33(Group._43_3, "Floor and wall covering"),
	_43_34(Group._43_3, "Painting and glazing"),
	_43_39(Group._43_3, "Other building completion and finishing"),
	_43_91(Group._43_9, "Roofing activities"),
	_43_99(Group._43_9, "Other specialised construction activities n.e.c."),
	_45_11(Group._45_1, "Sale of cars and light motor vehicles"),
	_45_19(Group._45_1, "Sale of other motor vehicles"),
	_45_2(Group._45_2, "Maintenance and repair of motor vehicles"),
	_45_31(Group._45_3, "Wholesale trade of motor vehicle parts and accessories"),
	_45_32(Group._45_3, "Retail trade of motor vehicle parts and accessories"),
	_45_4(Group._45_4, "Sale, maintenance and repair of motorcycles and related parts and accessories"),
	_46_11(Group._46_1, "Agents involved in the sale of agricultural raw materials, live animals, textile raw materials and semi-finished goods"),
	_46_12(Group._46_1, "Agents involved in the sale of fuels, ores, metals and industrial chemicals"),
	_46_13(Group._46_1, "Agents involved in the sale of timber and building materials"),
	_46_14(Group._46_1, "Agents involved in the sale of machinery, industrial equipment, ships and aircraft"),
	_46_15(Group._46_1, "Agents involved in the sale of furniture, household goods, hardware and ironmongery"),
	_46_16(Group._46_1, "Agents involved in the sale of textiles, clothing, fur, footwear and leather goods"),
	_46_17(Group._46_1, "Agents involved in the sale of food, beverages and tobacco"),
	_46_18(Group._46_1, "Agents specialised in the sale of other particular products"),
	_46_19(Group._46_1, "Agents involved in the sale of a variety of goods"),
	_46_21(Group._46_2, "Wholesale of grain, unmanufactured tobacco, seeds and animal feeds"),
	_46_22(Group._46_2, "Wholesale of flowers and plants"),
	_46_23(Group._46_2, "Wholesale of live animals"),
	_46_24(Group._46_2, "Wholesale of hides, skins and leather"),
	_46_31(Group._46_3, "Wholesale of fruit and vegetables"),
	_46_32(Group._46_3, "Wholesale of meat and meat products"),
	_46_33(Group._46_3, "Wholesale of dairy products, eggs and edible oils and fats"),
	_46_34(Group._46_3, "Wholesale of beverages"),
	_46_35(Group._46_3, "Wholesale of tobacco products"),
	_46_36(Group._46_3, "Wholesale of sugar and chocolate and sugar confectionery"),
	_46_37(Group._46_3, "Wholesale of coffee, tea, cocoa and spices"),
	_46_38(Group._46_3, "Wholesale of other food, including fish, crustaceans and molluscs"),
	_46_39(Group._46_3, "Non-specialised wholesale of food, beverages and tobacco"),
	_46_41(Group._46_4, "Wholesale of textiles"),
	_46_42(Group._46_4, "Wholesale of clothing and footwear"),
	_46_43(Group._46_4, "Wholesale of electrical household appliances"),
	_46_44(Group._46_4, "Wholesale of china and glassware and cleaning materials"),
	_46_45(Group._46_4, "Wholesale of perfume and cosmetics"),
	_46_46(Group._46_4, "Wholesale of pharmaceutical goods"),
	_46_47(Group._46_4, "Wholesale of furniture, carpets and lighting equipment"),
	_46_48(Group._46_4, "Wholesale of watches and jewellery"),
	_46_49(Group._46_4, "Wholesale of other household goods"),
	_46_51(Group._46_5, "Wholesale of computers, computer peripheral equipment and software"),
	_46_52(Group._46_5, "Wholesale of electronic and telecommunications equipment and parts"),
	_46_61(Group._46_6, "Wholesale of agricultural machinery, equipment and supplies"),
	_46_62(Group._46_6, "Wholesale of machine tools"),
	_46_63(Group._46_6, "Wholesale of mining, construction and civil engineering machinery"),
	_46_64(Group._46_6, "Wholesale of machinery for the textile industry and of sewing and knitting machines"),
	_46_65(Group._46_6, "Wholesale of office furniture"),
	_46_66(Group._46_6, "Wholesale of other office machinery and equipment"),
	_46_69(Group._46_6, "Wholesale of other machinery and equipment"),
	_46_71(Group._46_7, "Wholesale of solid, liquid and gaseous fuels and related products"),
	_46_72(Group._46_7, "Wholesale of metals and metal ores"),
	_46_73(Group._46_7, "Wholesale of wood, construction materials and sanitary equipment"),
	_46_74(Group._46_7, "Wholesale of hardware, plumbing and heating equipment and supplies"),
	_46_75(Group._46_7, "Wholesale of chemical products"),
	_46_76(Group._46_7, "Wholesale of other intermediate products"),
	_46_77(Group._46_7, "Wholesale of waste and scrap"),
	_46_9(Group._46_9, "Non-specialised wholesale trade"),
	_47_11(Group._47_1, "Retail sale in non-specialised stores with food, beverages or tobacco predominating"),
	_47_19(Group._47_1, "Other retail sale in non-specialised stores"),
	_47_21(Group._47_2, "Retail sale of fruit and vegetables in specialised stores"),
	_47_22(Group._47_2, "Retail sale of meat and meat products in specialised stores"),
	_47_23(Group._47_2, "Retail sale of fish, crustaceans and molluscs in specialised stores"),
	_47_24(Group._47_2, "Retail sale of bread, cakes, flour confectionery and sugar confectionery in specialised stores"),
	_47_25(Group._47_2, "Retail sale of beverages in specialised stores"),
	_47_26(Group._47_2, "Retail sale of tobacco products in specialised stores"),
	_47_29(Group._47_2, "Other retail sale of food in specialised stores"),
	_47_3(Group._47_3, "Retail sale of automotive fuel in specialised stores"),
	_47_41(Group._47_4, "Retail sale of computers, peripheral units and software in specialised stores"),
	_47_42(Group._47_4, "Retail sale of telecommunications equipment in specialised stores"),
	_47_43(Group._47_4, "Retail sale of audio and video equipment in specialised stores"),
	_47_51(Group._47_5, "Retail sale of textiles in specialised stores"),
	_47_52(Group._47_5, "Retail sale of hardware, paints and glass in specialised stores"),
	_47_53(Group._47_5, "Retail sale of carpets, rugs, wall and floor coverings in specialised stores"),
	_47_54(Group._47_5, "Retail sale of electrical household appliances in specialised stores"),
	_47_59(Group._47_5, "Retail sale of furniture, lighting equipment and other household articles in specialised stores"),
	_47_61(Group._47_6, "Retail sale of books in specialised stores"),
	_47_62(Group._47_6, "Retail sale of newspapers and stationery in specialised stores"),
	_47_63(Group._47_6, "Retail sale of music and video recordings in specialised stores"),
	_47_64(Group._47_6, "Retail sale of sporting equipment in specialised stores"),
	_47_65(Group._47_6, "Retail sale of games and toys in specialised stores"),
	_47_71(Group._47_7, "Retail sale of clothing in specialised stores"),
	_47_72(Group._47_7, "Retail sale of footwear and leather goods in specialised stores"),
	_47_73(Group._47_7, "Dispensing chemist in specialised stores"),
	_47_74(Group._47_7, "Retail sale of medical and orthopaedic goods in specialised stores"),
	_47_75(Group._47_7, "Retail sale of cosmetic and toilet articles in specialised stores"),
	_47_76(Group._47_7, "Retail sale of flowers, plants, seeds, fertilisers, pet animals and pet food in specialised stores"),
	_47_77(Group._47_7, "Retail sale of watches and jewellery in specialised stores"),
	_47_78(Group._47_7, "Other retail sale of new goods in specialised stores"),
	_47_79(Group._47_7, "Retail sale of second-hand goods in stores"),
	_47_81(Group._47_8, "Retail sale via stalls and markets of food, beverages and tobacco products"),
	_47_82(Group._47_8, "Retail sale via stalls and markets of textiles, clothing and footwear"),
	_47_89(Group._47_8, "Retail sale via stalls and markets of other goods"),
	_47_91(Group._47_9, "Retail sale via mail order houses or via Internet"),
	_47_99(Group._47_9, "Other retail sale not in stores, stalls or markets"),
	_49_1(Group._49_1, "Passenger rail transport, interurban"),
	_49_2(Group._49_2, "Freight rail transport"),
	_49_31(Group._49_3, "Urban and suburban passenger land transport"),
	_49_32(Group._49_3, "Taxi operation"),
	_49_39(Group._49_3, "Other passenger land transport n.e.c."),
	_49_41(Group._49_4, "Freight transport by road"),
	_49_42(Group._49_4, "Removal services"),
	_49_5(Group._49_5, "Transport via pipeline"),
	_50_1(Group._50_1, "Sea and coastal passenger water transport"),
	_50_2(Group._50_2, "Sea and coastal freight water transport"),
	_50_3(Group._50_3, "Inland passenger water transport"),
	_50_4(Group._50_4, "Inland freight water transport"),
	_51_1(Group._51_1, "Passenger air transport"),
	_51_21(Group._51_2, "Freight air transport"),
	_51_22(Group._51_2, "Space transport"),
	_52_1(Group._52_1, "Warehousing and storage"),
	_52_21(Group._52_2, "Service activities incidental to land transportation"),
	_52_22(Group._52_2, "Service activities incidental to water transportation"),
	_52_23(Group._52_2, "Service activities incidental to air transportation"),
	_52_24(Group._52_2, "Cargo handling"),
	_52_29(Group._52_2, "Other transportation support activities "),
	_53_1(Group._53_1, "Postal activities under universal service obligation"),
	_53_2(Group._53_2, "Other postal and courier activities"),
	_55_1(Group._55_1, "Hotels and similar accommodation"),
	_55_2(Group._55_2, "Holiday and other short-stay accommodation"),
	_55_3(Group._55_3, "Camping grounds, recreational vehicle parks and trailer parks"),
	_55_9(Group._55_9, "Other accommodation"),
	_56_1(Group._56_1, "Restaurants and mobile food service activities"),
	_56_21(Group._56_2, "Event catering activities"),
	_56_29(Group._56_2, "Other food service activities"),
	_56_3(Group._56_3, "Beverage serving activities"),
	_58_11(Group._58_1, "Book publishing"),
	_58_12(Group._58_1, "Publishing of directories and mailing lists"),
	_58_13(Group._58_1, "Publishing of newspapers"),
	_58_14(Group._58_1, "Publishing of journals and periodicals"),
	_58_19(Group._58_1, "Other publishing activities"),
	_58_21(Group._58_2, "Publishing of computer games"),
	_58_29(Group._58_2, "Other software publishing"),
	_59_11(Group._59_1, "Motion picture, video and television programme production activities"),
	_59_12(Group._59_1, "Motion picture, video and television programme post-production activities"),
	_59_13(Group._59_1, "Motion picture, video and television programme distribution activities"),
	_59_14(Group._59_1, "Motion picture projection activities"),
	_59_2(Group._59_2, "Sound recording and music publishing activities"),
	_60_1(Group._60_1, "Radio broadcasting"),
	_60_2(Group._60_2, "Television programming and broadcasting activities"),
	_61_1(Group._61_1, "Wired telecommunications activities"),
	_61_2(Group._61_2, "Wireless telecommunications activities"),
	_61_3(Group._61_3, "Satellite telecommunications activities"),
	_61_9(Group._61_9, "Other telecommunications activities"),
	_62_01(Group._62__, "Computer programming activities"),
	_62_02(Group._62__, "Computer consultancy activities"),
	_62_03(Group._62__, "Computer facilities management activities"),
	_62_09(Group._62__, "Other information technology and computer service activities"),
	_63_11(Group._63_1, "Data processing, hosting and related activities"),
	_63_12(Group._63_1, "Web portals"),
	_63_91(Group._63_9, "News agency activities"),
	_63_99(Group._63_9, "Other information service activities n.e.c."),
	_64_11(Group._64_1, "Central banking"),
	_64_19(Group._64_1, "Other monetary intermediation"),
	_64_2(Group._64_2, "Activities of holding companies"),
	_64_3(Group._64_3, "Trusts, funds and similar financial entities"),
	_64_91(Group._64_9, "Financial leasing"),
	_64_92(Group._64_9, "Other credit granting"),
	_64_99(Group._64_9, "Other financial service activities, except insurance and pension funding n.e.c."),
	_65_11(Group._65_1, "Life insurance"),
	_65_12(Group._65_1, "Non-life insurance"),
	_65_2(Group._65_2, "Reinsurance"),
	_65_3(Group._65_3, "Pension funding"),
	_66_11(Group._66_1, "Administration of financial markets"),
	_66_12(Group._66_1, "Security and commodity contracts brokerage"),
	_66_19(Group._66_1, "Other activities auxiliary to financial services, except insurance and pension funding"),
	_66_21(Group._66_2, "Risk and damage evaluation"),
	_66_22(Group._66_2, "Activities of insurance agents and brokers"),
	_66_29(Group._66_2, "Other activities auxiliary to insurance and pension funding"),
	_66_3(Group._66_3, "Fund management activities"),
	_68_1(Group._68_1, "Buying and selling of own real estate"),
	_68_2(Group._68_2, "Rental and operating of own or leased real estate"),
	_68_31(Group._68_3, "Real estate agencies"),
	_68_32(Group._68_3, "Management of real estate on a fee or contract basis"),
	_69_1(Group._69_1, "Legal activities"),
	_69_2(Group._69_2, "Accounting, bookkeeping and auditing activities; tax consultancy"),
	_70_1(Group._70_1, "Activities of head offices"),
	_70_21(Group._70_2, "Public relations and communication activities"),
	_70_22(Group._70_2, "Business and other management consultancy activities"),
	_71_11(Group._71_1, "Architectural activities "),
	_71_12(Group._71_1, "Engineering activities and related technical consultancy"),
	_71_2(Group._71_2, "Technical testing and analysis"),
	_72_11(Group._72_1, "Research and experimental development on biotechnology"),
	_72_19(Group._72_1, "Other research and experimental development on natural sciences and engineering"),
	_72_2(Group._72_2, "Research and experimental development on social sciences and humanities"),
	_73_11(Group._73_1, "Advertising agencies"),
	_73_12(Group._73_1, "Media representation"),
	_73_2(Group._73_2, "Market research and public opinion polling"),
	_74_1(Group._74_1, "Specialised design activities"),
	_74_2(Group._74_2, "Photographic activities"),
	_74_3(Group._74_3, "Translation and interpretation activities"),
	_74_9(Group._74_9, "Other professional, scientific and technical activities n.e.c."),
	_75(Group._75__, "Veterinary activities"),
	_77_11(Group._77_1, "Rental and leasing of cars and light motor vehicles"),
	_77_12(Group._77_1, "Rental and leasing of trucks"),
	_77_21(Group._77_2, "Rental and leasing of recreational and sports goods"),
	_77_22(Group._77_2, "Rental of video tapes and disks"),
	_77_29(Group._77_2, "Rental and leasing of other personal and household goods"),
	_77_31(Group._77_3, "Rental and leasing of agricultural machinery and equipment"),
	_77_32(Group._77_3, "Rental and leasing of construction and civil engineering machinery and equipment"),
	_77_33(Group._77_3, "Rental and leasing of office machinery and equipment (including computers)"),
	_77_34(Group._77_3, "Rental and leasing of water transport equipment"),
	_77_35(Group._77_3, "Rental and leasing of air transport equipment"),
	_77_39(Group._77_3, "Rental and leasing of other machinery, equipment and tangible goods n.e.c."),
	_77_4(Group._77_4, "Leasing of intellectual property and similar products, except copyrighted works"),
	_78_1(Group._78_1, "Activities of employment placement agencies"),
	_78_2(Group._78_2, "Temporary employment agency activities"),
	_78_3(Group._78_3, "Other human resources provision"),
	_79_11(Group._79_1, "Travel agency activities"),
	_79_12(Group._79_1, "Tour operator activities"),
	_79_9(Group._79_9, "Other reservation service and related activities"),
	_80_1(Group._80_1, "Private security activities"),
	_80_2(Group._80_2, "Security systems service activities"),
	_80_3(Group._80_3, "Investigation activities"),
	_81_1(Group._81_1, "Combined facilities support activities"),
	_81_21(Group._81_2, "General cleaning of buildings"),
	_81_22(Group._81_2, "Other building and industrial cleaning activities"),
	_81_29(Group._81_2, "Other cleaning activities"),
	_81_3(Group._81_3, "Landscape service activities"),
	_82_11(Group._82_1, "Combined office administrative service activities"),
	_82_19(Group._82_1, "Photocopying, document preparation and other specialised office support activities"),
	_82_2(Group._82_2, "Activities of call centres"),
	_82_3(Group._82_3, "Organisation of conventions and trade shows"),
	_82_91(Group._82_9, "Activities of collection agencies and credit bureaus"),
	_82_92(Group._82_9, "Packaging activities"),
	_82_99(Group._82_9, "Other business support service activities n.e.c."),
	_84_11(Group._84_1, "General public administration activities"),
	_84_12(Group._84_1, "Regulation of the activities of providing health care, education, cultural services and other social services, excluding social security"),
	_84_13(Group._84_1, "Regulation of and contribution to more efficient operation of businesses"),
	_84_21(Group._84_2, "Foreign affairs"),
	_84_22(Group._84_2, "Defence activities"),
	_84_23(Group._84_2, "Justice and judicial activities"),
	_84_24(Group._84_2, "Public order and safety activities"),
	_84_25(Group._84_2, "Fire service activities"),
	_84_3(Group._84_3, "Compulsory social security activities"),
	_85_1(Group._85_1, "Pre-primary education "),
	_85_2(Group._85_2, "Primary education "),
	_85_31(Group._85_3, "General secondary education "),
	_85_32(Group._85_3, "Technical and vocational secondary education "),
	_85_41(Group._85_4, "Post-secondary non-tertiary education"),
	_85_42(Group._85_4, "Tertiary education"),
	_85_51(Group._85_5, "Sports and recreation education"),
	_85_52(Group._85_5, "Cultural education"),
	_85_53(Group._85_5, "Driving school activities"),
	_85_59(Group._85_5, "Other education n.e.c."),
	_85_6(Group._85_6, "Educational support activities"),
	_86_1(Group._86_1, "Hospital activities"),
	_86_21(Group._86_2, "General medical practice activities"),
	_86_22(Group._86_2, "Specialist medical practice activities"),
	_86_23(Group._86_2, "Dental practice activities"),
	_86_9(Group._86_9, "Other human health activities"),
	_87_1(Group._87_1, "Residential nursing care activities"),
	_87_2(Group._87_2, "Residential care activities for mental retardation, mental health and substance abuse"),
	_87_3(Group._87_3, "Residential care activities for the elderly and disabled"),
	_87_9(Group._87_9, "Other residential care activities"),
	_88_1(Group._88_1, "Social work activities without accommodation for the elderly and disabled"),
	_88_91(Group._88_9, "Child day-care activities"),
	_88_99(Group._88_9, "Other social work activities without accommodation n.e.c."),
	_90_01(Group._90__, "Performing arts"),
	_90_02(Group._90__, "Support activities to performing arts"),
	_90_03(Group._90__, "Artistic creation"),
	_90_04(Group._90__, "Operation of arts facilities"),
	_91_01(Group._91__, "Library and archives activities"),
	_91_02(Group._91__, "Museums activities"),
	_91_03(Group._91__, "Operation of historical sites and buildings and similar visitor attractions"),
	_91_04(Group._91__, "Botanical and zoological gardens and nature reserves activities"),
	_92(Group._92__, "Gambling and betting activities"),
	_93_11(Group._93_1, "Operation of sports facilities"),
	_93_12(Group._93_1, "Activities of sports clubs"),
	_93_13(Group._93_1, "Fitness facilities"),
	_93_19(Group._93_1, "Other sports activities"),
	_93_21(Group._93_2, "Activities of amusement parks and theme parks"),
	_93_29(Group._93_2, "Other amusement and recreation activities"),
	_94_11(Group._94_1, "Activities of business and employers membership organisations"),
	_94_12(Group._94_1, "Activities of professional membership organisations"),
	_94_2(Group._94_2, "Activities of trade unions"),
	_94_91(Group._94_9, "Activities of religious organisations"),
	_94_92(Group._94_9, "Activities of political organisations"),
	_94_99(Group._94_9, "Activities of other membership organisations n.e.c."),
	_95_11(Group._95_1, "Repair of computers and peripheral equipment"),
	_95_12(Group._95_1, "Repair of communication equipment"),
	_95_21(Group._95_2, "Repair of consumer electronics"),
	_95_22(Group._95_2, "Repair of household appliances and home and garden equipment"),
	_95_23(Group._95_2, "Repair of footwear and leather goods"),
	_95_24(Group._95_2, "Repair of furniture and home furnishings"),
	_95_25(Group._95_2, "Repair of watches, clocks and jewellery"),
	_95_29(Group._95_2, "Repair of other personal and household goods"),
	_96_01(Group._96__, "Washing and (dry-)cleaning of textile and fur products"),
	_96_02(Group._96__, "Hairdressing and other beauty treatment"),
	_96_03(Group._96__, "Funeral and related activities"),
	_96_04(Group._96__, "Physical well-being activities"),
	_96_09(Group._96__, "Other personal service activities n.e.c."),
	_97(Group._97__, "Activities of households as employers of domestic personnel"),
	_98_1(Group._98_1, "Undifferentiated goods-producing activities of private households for own use"),
	_98_2(Group._98_2, "Undifferentiated service-producing activities of private households for own use"),
	_99(Group._99__, "Activities of extraterritorial organisations and bodies");

	private final Group group;
	private final String title;
	private Class(Group group, String title) {
		this.group = group;
		this.title = title;
	}

}
