package be.ceau.nace;

public enum Group {

	_01_1(Division._01, "Growing of non-perennial crops"),
	_01_2(Division._01, "Growing of perennial crops"),
	_01_3(Division._01, "Plant propagation"),
	_01_4(Division._01, "Animal production"),
	_01_5(Division._01, "Mixed farming"),
	_01_6(Division._01, "Support activities to agriculture and post-harvest crop activities"),
	_01_7(Division._01, "Hunting, trapping and related service activities"),
	_02_1(Division._02, "Silviculture and other forestry activities"),
	_02_2(Division._02, "Logging"),
	_02_3(Division._02, "Gathering of wild growing non-wood products"),
	_02_4(Division._02, "Support services to forestry"),
	_03_1(Division._03, "Fishing"),
	_03_2(Division._03, "Aquaculture"),
	_05_1(Division._05, "Mining of hard coal"),
	_05_2(Division._05, "Mining of lignite"),
	_06_1(Division._06, "Extraction of crude petroleum"),
	_06_2(Division._06, "Extraction of natural gas"),
	_07_1(Division._07, "Mining of iron ores"),
	_07_2(Division._07, "Mining of non-ferrous metal ores"),
	_08_1(Division._08, "Quarrying of stone, sand and clay"),
	_08_9(Division._08, "Mining and quarrying n.e.c."),
	_09_1(Division._09, "Support activities for petroleum and natural gas extraction"),
	_09_9(Division._09, "Support activities for other mining and quarrying"),
	_10_1(Division._10, "Processing and preserving of meat and production of meat products"),
	_10_2(Division._10, "Processing and preserving of fish, crustaceans and molluscs"),
	_10_3(Division._10, "Processing and preserving of fruit and vegetables"),
	_10_4(Division._10, "Manufacture of vegetable and animal oils and fats"),
	_10_5(Division._10, "Manufacture of dairy products"),
	_10_6(Division._10, "Manufacture of grain mill products, starches and starch products"),
	_10_7(Division._10, "Manufacture of bakery and farinaceous products"),
	_10_8(Division._10, "Manufacture of other food products"),
	_10_9(Division._10, "Manufacture of prepared animal feeds"),
	_11__(Division._11, "Manufacture of beverages"),
	_12__(Division._12, "Manufacture of tobacco products"),
	_13_1(Division._13, "Preparation and spinning of textile fibres"),
	_13_2(Division._13, "Weaving of textiles"),
	_13_3(Division._13, "Finishing of textiles"),
	_13_9(Division._13, "Manufacture of other textiles"),
	_14_1(Division._14, "Manufacture of wearing apparel, except fur apparel"),
	_14_2(Division._14, "Manufacture of articles of fur"),
	_14_3(Division._14, "Manufacture of knitted and crocheted apparel"),
	_15_1(Division._15, "Tanning and dressing of leather; manufacture of luggage, handbags, saddlery and harness; dressing and dyeing of fur"),
	_15_2(Division._15, "Manufacture of footwear"),
	_16_1(Division._16, "Sawmilling and planing of wood"),
	_16_2(Division._16, "Manufacture of products of wood, cork, straw and plaiting materials"),
	_17_1(Division._17, "Manufacture of pulp, paper and paperboard"),
	_17_2(Division._17, "Manufacture of articles of paper and paperboard "),
	_18_1(Division._18, "Printing and service activities related to printing"),
	_18_2(Division._18, "Reproduction of recorded media"),
	_19_1(Division._19, "Manufacture of coke oven products"),
	_19_2(Division._19, "Manufacture of refined petroleum products"),
	_20_1(Division._20, "Manufacture of basic chemicals, fertilisers and nitrogen compounds, plastics and synthetic rubber in primary forms"),
	_20_2(Division._20, "Manufacture of pesticides and other agrochemical products"),
	_20_3(Division._20, "Manufacture of paints, varnishes and similar coatings, printing ink and mastics"),
	_20_4(Division._20, "Manufacture of soap and detergents, cleaning and polishing preparations, perfumes and toilet preparations"),
	_20_5(Division._20, "Manufacture of other chemical products"),
	_20_6(Division._20, "Manufacture of man-made fibres"),
	_21_1(Division._21, "Manufacture of basic pharmaceutical products"),
	_21_2(Division._21, "Manufacture of pharmaceutical preparations"),
	_22_1(Division._22, "Manufacture of rubber products"),
	_22_2(Division._22, "Manufacture of plastic products"),
	_23_1(Division._23, "Manufacture of glass and glass products"),
	_23_2(Division._23, "Manufacture of refractory products"),
	_23_3(Division._23, "Manufacture of clay building materials"),
	_23_4(Division._23, "Manufacture of other porcelain and ceramic products"),
	_23_5(Division._23, "Manufacture of cement, lime and plaster"),
	_23_6(Division._23, "Manufacture of articles of concrete, cement and plaster"),
	_23_7(Division._23, "Cutting, shaping and finishing of stone"),
	_23_9(Division._23, "Manufacture of abrasive products and non-metallic mineral products n.e.c."),
	_24_1(Division._24, "Manufacture of basic iron and steel and of ferro-alloys"),
	_24_2(Division._24, "Manufacture of tubes, pipes, hollow profiles and related fittings, of steel"),
	_24_3(Division._24, "Manufacture of other products of first processing of steel"),
	_24_4(Division._24, "Manufacture of basic precious and other non-ferrous metals"),
	_24_5(Division._24, "Casting of metals"),
	_25_1(Division._25, "Manufacture of structural metal products"),
	_25_2(Division._25, "Manufacture of tanks, reservoirs and containers of metal"),
	_25_3(Division._25, "Manufacture of steam generators, except central heating hot water boilers"),
	_25_4(Division._25, "Manufacture of weapons and ammunition"),
	_25_5(Division._25, "Forging, pressing, stamping and roll-forming of metal; powder metallurgy"),
	_25_6(Division._25, "Treatment and coating of metals; machining"),
	_25_7(Division._25, "Manufacture of cutlery, tools and general hardware"),
	_25_9(Division._25, "Manufacture of other fabricated metal products"),
	_26_1(Division._26, "Manufacture of electronic components and boards"),
	_26_2(Division._26, "Manufacture of computers and peripheral equipment"),
	_26_3(Division._26, "Manufacture of communication equipment"),
	_26_4(Division._26, "Manufacture of consumer electronics"),
	_26_5(Division._26, "Manufacture of instruments and appliances for measuring, testing and navigation; watches and clocks"),
	_26_6(Division._26, "Manufacture of irradiation, electromedical and electrotherapeutic equipment"),
	_26_7(Division._26, "Manufacture of optical instruments and photographic equipment"),
	_26_8(Division._26, "Manufacture of magnetic and optical media"),
	_27_1(Division._27, "Manufacture of electric motors, generators, transformers and electricity distribution and control apparatus"),
	_27_2(Division._27, "Manufacture of batteries and accumulators"),
	_27_3(Division._27, "Manufacture of wiring and wiring devices"),
	_27_4(Division._27, "Manufacture of electric lighting equipment"),
	_27_5(Division._27, "Manufacture of domestic appliances"),
	_27_9(Division._27, "Manufacture of other electrical equipment"),
	_28_1(Division._28, "Manufacture of general-purpose machinery"),
	_28_2(Division._28, "Manufacture of other general-purpose machinery"),
	_28_3(Division._28, "Manufacture of agricultural and forestry machinery"),
	_28_4(Division._28, "Manufacture of metal forming machinery and machine tools"),
	_28_9(Division._28, "Manufacture of other special-purpose machinery"),
	_29_1(Division._29, "Manufacture of motor vehicles"),
	_29_2(Division._29, "Manufacture of bodies (coachwork) for motor vehicles; manufacture of trailers and semi-trailers"),
	_29_3(Division._29, "Manufacture of parts and accessories for motor vehicles"),
	_30_1(Division._30, "Building of ships and boats"),
	_30_2(Division._30, "Manufacture of railway locomotives and rolling stock"),
	_30_3(Division._30, "Manufacture of air and spacecraft and related machinery"),
	_30_4(Division._30, "Manufacture of military fighting vehicles"),
	_30_9(Division._30, "Manufacture of transport equipment n.e.c."),
	_31__(Division._31, "Manufacture of furniture"),
	_32_1(Division._32, "Manufacture of jewellery, bijouterie and related articles"),
	_32_2(Division._32, "Manufacture of musical instruments"),
	_32_3(Division._32, "Manufacture of sports goods"),
	_32_4(Division._32, "Manufacture of games and toys"),
	_32_5(Division._32, "Manufacture of medical and dental instruments and supplies"),
	_32_9(Division._32, "Manufacturing n.e.c."),
	_33_1(Division._33, "Repair of fabricated metal products, machinery and equipment"),
	_33_2(Division._33, "Installation of industrial machinery and equipment"),
	_35_1(Division._35, "Electric power generation, transmission and distribution"),
	_35_2(Division._35, "Manufacture of gas; distribution of gaseous fuels through mains"),
	_35_3(Division._35, "Steam and air conditioning supply"),
	_36__(Division._36, "Water collection, treatment and supply"),
	_37__(Division._37, "Sewerage"),
	_38_1(Division._38, "Waste collection"),
	_38_2(Division._38, "Waste treatment and disposal"),
	_38_3(Division._38, "Materials recovery"),
	_39__(Division._39, "Remediation activities and other waste management services"),
	_41_1(Division._41, "Development of building projects"),
	_41_2(Division._41, "Construction of residential and non-residential buildings"),
	_42_1(Division._42, "Construction of roads and railways"),
	_42_2(Division._42, "Construction of utility projects"),
	_42_9(Division._42, "Construction of other civil engineering projects"),
	_43_1(Division._43, "Demolition and site preparation"),
	_43_2(Division._43, "Electrical, plumbing and other construction installation activities"),
	_43_3(Division._43, "Building completion and finishing"),
	_43_9(Division._43, "Other specialised construction activities"),
	_45_1(Division._45, "Sale of motor vehicles"),
	_45_2(Division._45, "Maintenance and repair of motor vehicles"),
	_45_3(Division._45, "Sale of motor vehicle parts and accessories"),
	_45_4(Division._45, "Sale, maintenance and repair of motorcycles and related parts and accessories"),
	_46_1(Division._46, "Wholesale on a fee or contract basis"),
	_46_2(Division._46, "Wholesale of agricultural raw materials and live animals"),
	_46_3(Division._46, "Wholesale of food, beverages and tobacco"),
	_46_4(Division._46, "Wholesale of household goods"),
	_46_5(Division._46, "Wholesale of information and communication equipment"),
	_46_6(Division._46, "Wholesale of other machinery, equipment and supplies"),
	_46_7(Division._46, "Other specialised wholesale"),
	_46_9(Division._46, "Non-specialised wholesale trade"),
	_47_1(Division._47, "Retail sale in non-specialised stores"),
	_47_2(Division._47, "Retail sale of food, beverages and tobacco in specialised stores"),
	_47_3(Division._47, "Retail sale of automotive fuel in specialised stores"),
	_47_4(Division._47, "Retail sale of information and communication equipment in specialised stores"),
	_47_5(Division._47, "Retail sale of other household equipment in specialised stores"),
	_47_6(Division._47, "Retail sale of cultural and recreation goods in specialised stores"),
	_47_7(Division._47, "Retail sale of other goods in specialised stores"),
	_47_8(Division._47, "Retail sale via stalls and markets"),
	_47_9(Division._47, "Retail trade not in stores, stalls or markets"),
	_49_1(Division._49, "Passenger rail transport, interurban"),
	_49_2(Division._49, "Freight rail transport"),
	_49_3(Division._49, "Other passenger land transport "),
	_49_4(Division._49, "Freight transport by road and removal services"),
	_49_5(Division._49, "Transport via pipeline"),
	_50_1(Division._50, "Sea and coastal passenger water transport"),
	_50_2(Division._50, "Sea and coastal freight water transport"),
	_50_3(Division._50, "Inland passenger water transport"),
	_50_4(Division._50, "Inland freight water transport"),
	_51_1(Division._51, "Passenger air transport"),
	_51_2(Division._51, "Freight air transport and space transport"),
	_52_1(Division._52, "Warehousing and storage"),
	_52_2(Division._52, "Support activities for transportation"),
	_53_1(Division._53, "Postal activities under universal service obligation"),
	_53_2(Division._53, "Other postal and courier activities"),
	_55_1(Division._55, "Hotels and similar accommodation"),
	_55_2(Division._55, "Holiday and other short-stay accommodation"),
	_55_3(Division._55, "Camping grounds, recreational vehicle parks and trailer parks"),
	_55_9(Division._55, "Other accommodation"),
	_56_1(Division._56, "Restaurants and mobile food service activities"),
	_56_2(Division._56, "Event catering and other food service activities"),
	_56_3(Division._56, "Beverage serving activities"),
	_58_1(Division._58, "Publishing of books, periodicals and other publishing activities"),
	_58_2(Division._58, "Software publishing"),
	_59_1(Division._59, "Motion picture, video and television programme activities"),
	_59_2(Division._59, "Sound recording and music publishing activities"),
	_60_1(Division._60, "Radio broadcasting"),
	_60_2(Division._60, "Television programming and broadcasting activities"),
	_61_1(Division._61, "Wired telecommunications activities"),
	_61_2(Division._61, "Wireless telecommunications activities"),
	_61_3(Division._61, "Satellite telecommunications activities"),
	_61_9(Division._61, "Other telecommunications activities"),
	_62__(Division._62, "Computer programming, consultancy and related activities"),
	_63_1(Division._63, "Data processing, hosting and related activities; web portals"),
	_63_9(Division._63, "Other information service activities"),
	_64_1(Division._64, "Monetary intermediation"),
	_64_2(Division._64, "Activities of holding companies"),
	_64_3(Division._64, "Trusts, funds and similar financial entities"),
	_64_9(Division._64, "Other financial service activities, except insurance and pension funding"),
	_65_1(Division._65, "Insurance"),
	_65_2(Division._65, "Reinsurance"),
	_65_3(Division._65, "Pension funding"),
	_66_1(Division._66, "Activities auxiliary to financial services, except insurance and pension funding"),
	_66_2(Division._66, "Activities auxiliary to insurance and pension funding"),
	_66_3(Division._66, "Fund management activities"),
	_68_1(Division._68, "Buying and selling of own real estate"),
	_68_2(Division._68, "Rental and operating of own or leased real estate"),
	_68_3(Division._68, "Real estate activities on a fee or contract basis"),
	_69_1(Division._69, "Legal activities"),
	_69_2(Division._69, "Accounting, bookkeeping and auditing activities; tax consultancy"),
	_70_1(Division._70, "Activities of head offices"),
	_70_2(Division._70, "Management consultancy activities"),
	_71_1(Division._71, "Architectural and engineering activities and related technical consultancy"),
	_71_2(Division._71, "Technical testing and analysis"),
	_72_1(Division._72, "Research and experimental development on natural sciences and engineering"),
	_72_2(Division._72, "Research and experimental development on social sciences and humanities"),
	_73_1(Division._73, "Advertising"),
	_73_2(Division._73, "Market research and public opinion polling"),
	_74_1(Division._74, "Specialised design activities"),
	_74_2(Division._74, "Photographic activities"),
	_74_3(Division._74, "Translation and interpretation activities"),
	_74_9(Division._74, "Other professional, scientific and technical activities n.e.c."),
	_75__(Division._75, "Veterinary activities"),
	_77_1(Division._77, "Rental and leasing of motor vehicles"),
	_77_2(Division._77, "Rental and leasing of personal and household goods"),
	_77_3(Division._77, "Rental and leasing of other machinery, equipment and tangible goods"),
	_77_4(Division._77, "Leasing of intellectual property and similar products, except copyrighted works"),
	_78_1(Division._78, "Activities of employment placement agencies"),
	_78_2(Division._78, "Temporary employment agency activities"),
	_78_3(Division._78, "Other human resources provision"),
	_79_1(Division._79, "Travel agency and tour operator activities"),
	_79_9(Division._79, "Other reservation service and related activities"),
	_80_1(Division._80, "Private security activities"),
	_80_2(Division._80, "Security systems service activities"),
	_80_3(Division._80, "Investigation activities"),
	_81_1(Division._81, "Combined facilities support activities"),
	_81_2(Division._81, "Cleaning activities"),
	_81_3(Division._81, "Landscape service activities"),
	_82_1(Division._82, "Office administrative and support activities"),
	_82_2(Division._82, "Activities of call centres"),
	_82_3(Division._82, "Organisation of conventions and trade shows"),
	_82_9(Division._82, "Business support service activities n.e.c."),
	_84_1(Division._84, "Administration of the State and the economic and social policy of the community"),
	_84_2(Division._84, "Provision of services to the community as a whole"),
	_84_3(Division._84, "Compulsory social security activities"),
	_85_1(Division._85, "Pre-primary education"),
	_85_2(Division._85, "Primary education"),
	_85_3(Division._85, "Secondary education"),
	_85_4(Division._85, "Higher education"),
	_85_5(Division._85, "Other education"),
	_85_6(Division._85, "Educational support activities"),
	_86_1(Division._86, "Hospital activities"),
	_86_2(Division._86, "Medical and dental practice activities"),
	_86_9(Division._86, "Other human health activities"),
	_87_1(Division._87, "Residential nursing care activities"),
	_87_2(Division._87, "Residential care activities for mental retardation, mental health and substance abuse"),
	_87_3(Division._87, "Residential care activities for the elderly and disabled"),
	_87_9(Division._87, "Other residential care activities"),
	_88_1(Division._88, "Social work activities without accommodation for the elderly and disabled"),
	_88_9(Division._88, "Other social work activities without accommodation"),
	_90__(Division._90, "Creative, arts and entertainment activities"),
	_91__(Division._91, "Libraries, archives, museums and other cultural activities"),
	_92__(Division._92, "Gambling and betting activities"),
	_93_1(Division._93, "Sports activities"),
	_93_2(Division._93, "Amusement and recreation activities"),
	_94_1(Division._94, "Activities of business, employers and professional membership organisations"),
	_94_2(Division._94, "Activities of trade unions"),
	_94_9(Division._94, "Activities of other membership organisations"),
	_95_1(Division._95, "Repair of computers and communication equipment"),
	_95_2(Division._95, "Repair of personal and household goods"),
	_96__(Division._96, "Other personal service activities"),
	_97__(Division._97, "Activities of households as employers of domestic personnel"),
	_98_1(Division._98, "Undifferentiated goods-producing activities of private households for own use"),
	_98_2(Division._98, "Undifferentiated service-producing activities of private households for own use"),
	_99__(Division._99, "Activities of extraterritorial organisations and bodies");

	private final Division division;
	private final String title;
	private Group(Division division, String title) {
		this.division = division;
		this.title = title;
	}

}
